INSERT INTO products (code, name, description, image_url, price) VALUES
('B001', 'Atomic Habits', 'An easy & proven way to build good habits & break bad ones.', 'https://example.com/images/atomic_habits.jpg', 499.00),
('B002', 'The Alchemist', 'A philosophical book about following your dreams.', 'https://example.com/images/the_alchemist.jpg', 399.00),
('B003', 'Rich Dad Poor Dad', 'What the rich teach their kids about money.', 'https://example.com/images/rich_dad_poor_dad.jpg', 450.00),
('B004', 'Ikigai', 'The Japanese secret to a long and happy life.', 'https://example.com/images/ikigai.jpg', 350.00),
('B005', 'The Psychology of Money', 'Timeless lessons on wealth, greed, and happiness.', 'https://example.com/images/psychology_of_money.jpg', 499.00),
('B006', 'Do Epic Shit', 'A collection of life learnings by Ankur Warikoo.', 'https://example.com/images/do_epic_shit.jpg', 399.00),
('B007', 'Deep Work', 'Rules for focused success in a distracted world.', 'https://example.com/images/deep_work.jpg', 525.00),
('B008', 'The Power of Now', 'A guide to spiritual enlightenment.', 'https://example.com/images/power_of_now.jpg', 475.00),
('B009', 'Think Like a Monk', 'Train your mind for peace and purpose.', 'https://example.com/images/think_like_a_monk.jpg', 430.00),
('B010', 'Can’t Hurt Me', 'Master your mind and defy the odds.', 'https://example.com/images/cant_hurt_me.jpg', 510.00),
('B011', 'You Can Win', 'A step-by-step tool for top achievers.', 'https://example.com/images/you_can_win.jpg', 299.00),
('B012', 'The Subtle Art of Not Giving a F*ck', 'A counterintuitive approach to living a good life.', 'https://example.com/images/subtle_art.jpg', 550.00),
('B013', 'Start With Why', 'How great leaders inspire everyone to take action.', 'https://example.com/images/start_with_why.jpg', 460.00),
('B014', 'The 5 AM Club', 'Own your morning. Elevate your life.', 'https://example.com/images/5am_club.jpg', 480.00),
('B015', 'Rework', 'Change the way you work forever.', 'https://example.com/images/rework.jpg', 420.00);
